### ISSUE TITLE
Reminder issues

### ISSUE THREAD

**Issue by nullnyan** [Spicadox/auto-twitter-space#1]
It will not work if a reminder is set.

`[ERROR] 'NoneType' object has no attribute 'strftime'`
https://github.com/Spicadox/auto-twitter-space/blob/b11791d1cc970e9672a57e3265c253eb300d17b7/twitter_space_bot.py#L153-L156

space[0] is `<Space id=id state=scheduled>`

I guess I need to add some handling of reminder exceptions...

**Comment by Spicadox** [comment]
Thanks for bring this up to me I didn't realize twitter spaces could be scheduled.
Problem fixed with the latest commit d6c1070.
I added a check for scheduled spaces and if one is encountered then it's ignored until it is live.

**Comment by nullnyan** [comment]
It worked fine!
Thank you very much!
