### ISSUE TITLE
possible to use a separate virtual environment

### ISSUE THREAD

**Issue by Lumerica** [Spicadox/auto-twitter-space#12]
Hi, I just stumbled upon your script and it looks really promising.
I want to try it out but I'd like to know how whether venv is supported or how to proceed using this without messing the local venv installed files as I various python scripts and want to avoid messing up with the dependencies.

**Comment by Spicadox** [comment]
I don't personally use venv(I should but eh), but I assume it should work out of the box if you create the virtual environment and then install the dependency into that environment as this is a python3 script and all other external dependencies will have to run
